name: "check-root-flake"

on:
  workflow_call:

jobs:
  check-root-flake:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Flake check
        run: nix flake check
