name: "CI"

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml
    secrets: inherit

  check-root-flake:
    needs: detect-changes
    if: needs.detect-changes.outputs.root == 'true'
    uses: ./.github/workflows/check-root-flake.yml
    secrets: inherit

  test-templates:
    needs: detect-changes
    if: needs.detect-changes.outputs.templates != '[]'
    uses: ./.github/workflows/test-templates.yml
    with:
      templates: ${{ needs.detect-changes.outputs.templates }}
    secrets: inherit

  test-haskell-template:
    needs: detect-changes
    if: needs.detect-changes.outputs.haskell == 'true'
    uses: ./.github/workflows/test-haskell-template.yml
    secrets: inherit

  ci-success:
    needs: [check-root-flake, test-templates, test-haskell-template]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Verify all checks passed
        run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
