name: "detect-changes"

on:
  workflow_call:
    outputs:
      templates:
        value: ${{ jobs.detect-changes.outputs.templates }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: List all templates
        id: list-templates
        uses: ./.github/actions/list-templates

      - name: Generate filters
        run: |
          echo "$TEMPLATES" | jq -r '.[] | "\(.):\n  - \"templates/\(.)/**\""' > filters.yml
        env:
          TEMPLATES: ${{ steps.list-templates.outputs.templates }}

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: filters.yml
