name: "flake-check"

on:
  workflow_call:
    inputs:
      templates:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  root:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Flake check (root)
        run: nix flake check

  templates-linux:
    if: inputs.templates != '[]'
    timeout-minutes: ${{ matrix.template == 'haskell' && 60 || 10 }}
    permissions:
      contents: read
    strategy:
      matrix:
        template: ${{ fromJSON(inputs.templates) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: gawakawa
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check ${{ matrix.template }} template
        working-directory: templates/${{ matrix.template }}
        run: nix flake check --accept-flake-config

  templates-macos:
    if: inputs.templates != '[]'
    timeout-minutes: 60
    permissions:
      contents: read
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: gawakawa
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check templates (macOS)
        env:
          TEMPLATES: ${{ inputs.templates }}
          MACOS_EXCLUDE: '["purs-nix", "haskell"]'
        run: |
          while IFS= read -r p; do nix flake check --accept-flake-config "$p"; done \
            < <(jq -r --argjson exclude "$MACOS_EXCLUDE" '.[] | select(IN($exclude[]) | not) | "./templates/\(.)"' <<< "$TEMPLATES")
