name: "test-templates"

on:
  workflow_call:
    inputs:
      templates:
        required: true
        type: string

jobs:
  test-templates:
    timeout-minutes: ${{ matrix.template == 'haskell' && 60 || 10 }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
        template: ${{ fromJSON(inputs.templates) }}
        exclude:
          - os: self-hosted
            template: purs-nix
          - os: self-hosted
            template: haskell
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: gawakawa
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check ${{ matrix.template }} template
        working-directory: templates/${{ matrix.template }}
        run: nix flake check ${{ matrix.template == 'haskell' && '--accept-flake-config' || '' }}

      - name: Test devShell for ${{ matrix.template }} template
        working-directory: templates/${{ matrix.template }}
        run: nix develop ${{ matrix.template == 'haskell' && '--accept-flake-config' || '' }} -c echo "DevShell works"
