name: "test-templates"

on:
  workflow_call:
    inputs:
      templates:
        required: true
        type: string

jobs:
  test-templates:
    timeout-minutes: ${{ matrix.template == 'haskell' && 60 || 10 }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
        template: ${{ fromJSON(inputs.templates) }}
        exclude:
          - os: self-hosted
            template: purs-nix
          - os: self-hosted
            template: haskell
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}

      - uses: cachix/cachix-action@97e5ff84d02b3b4f9936339f767e17f03c9252ed # v16
        with:
          name: gawakawa
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check ${{ matrix.template }} template
        working-directory: templates/${{ matrix.template }}
        run: nix flake check --accept-flake-config

      - name: Test devShell for ${{ matrix.template }} template
        working-directory: templates/${{ matrix.template }}
        run: nix develop --accept-flake-config -c echo "DevShell works"
